---
apiVersion: v1
kind: Namespace
metadata:
    name: apps
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-jenkins-pipeline-tester
  namespace: apps
  labels:
    app: k8s-jenkins-pipeline-tester
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-jenkins-pipeline-tester
  template:
    metadata:
      labels:
        app: k8s-jenkins-pipeline-tester
    spec:
      containers:
      - name: k8s-jenkins-pipeline-tester
        image: microdc/k8s-jenkins-pipeline-tester:develop
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        readinessProbe:
          timeoutSeconds: 10
          httpGet:
            path: /
            port: http
        livenessProbe:
          timeoutSeconds: 10
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 240
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-jenkins-pipeline-tester
  name: k8s-jenkins-pipeline-tester
  namespace: apps
spec:
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 5000
  selector:
    app: k8s-jenkins-pipeline-tester
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-jenkins-pipeline-tester
  name: k8s-jenkins-pipeline-tester-nodeport
  namespace: apps
spec:
  type: NodePort
  selector:
    app: k8s-jenkins-pipeline-tester
  ports:
  - port: 5000
    protocol: TCP
    name: http
    targetPort: 5000
  selector:
    app: k8s-jenkins-pipeline-tester
